# Generated by Django 3.1.7 on 2022-08-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status_unite',
            field=models.IntegerField(choices=[(0, 'Borrador'), (1, 'finalizado')], default=0),
        ),
    ]
