# Generated by Django 3.1.7 on 2022-07-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=None, max_length=300, unique=True),
        ),
    ]
