# Generated by Django 3.1.7 on 2022-08-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_status_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.IntegerField(choices=[(0, '-edit'), (1, '+edit')], default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status_unite',
            field=models.IntegerField(choices=[(0, '-edit'), (1, '+edit')], default=0),
        ),
    ]
