# Generated by Django 3.1.7 on 2022-08-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projects_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github',
            field=models.CharField(default='', max_length=150),
        ),
    ]
