# Generated by Django 3.1.7 on 2022-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projects_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(default='', upload_to='media/photos/project'),
        ),
    ]
