# Generated by Django 3.1.7 on 2022-07-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/user'),
        ),
    ]
