# Generated by Django 3.1.7 on 2022-08-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_user_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_head',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0),
        ),
    ]
