# Generated by Django 3.1.7 on 2022-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_user_profile_is_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='is_head',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='photo',
            field=models.ImageField(default='', upload_to='media/photos/user'),
        ),
    ]
