
// Authentication
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_STATUS = "SIGNUP_STATUS";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_STATUS = "LOGIN_STATUS"
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_SIGN_STATE = 'SET_SIGN_STATE';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


// listas de procesos
export const VIEW_NEW_PROJECT = "VIEW_NEW_PROJECT";
export const NEW_PROJECTS_SUCCESS = 'NEW_PROJECTS_SUCCESS';
export const NEW_PROJECTS_FAIL = 'NEW_PROJECTS_FAIL';
export const RESET_PROJECT_STATUS = 'RESET_PROJECT_STATUS';
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";
export const VIEW_EDIT_PROJECT = 'VIEW_EDIT_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const EDIT_PROJECTS_SUCCESS = 'EDIT_PROJECTS_SUCCESS';
export const EDIT_PROJECTS_FAIL = 'EDIT_PROJECTS_FAIL';
export const DELETE_PROJECTS_SUCCESS = 'DELETE_PROJECTS_SUCCESS';
export const DELETE_PROJECTS_FAIL = 'DELETE_PROJECTS_FAIL';
export const POST_PROJECT = 'POST_PROJECT';