# Generated by Django 3.1.7 on 2022-08-01 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('desc', models.TextField()),
                ('code', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/section')),
                ('status', models.IntegerField(choices=[(0, 'Borrador'), (1, 'finalizado')], default=0)),
                ('author', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
