# Generated by Django 3.1.7 on 2022-08-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_auto_20220801_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='photo_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
