# Generated by Django 3.1.7 on 2022-08-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_section_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='slug',
        ),
    ]
