# Generated by Django 3.1.7 on 2022-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_remove_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='photo',
            field=models.ImageField(default='', upload_to='media/photos/section'),
        ),
    ]
