# Generated by Django 3.1.7 on 2022-08-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='names',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
    ]
